{
 "title": "luizgustavo77-github",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "(rate(node_cpu_seconds_total{mode=\"user\"}[1m]))*100",
     "legendFormat": "User"
    },
    {
     "expr": "(rate(node_cpu_seconds_total{mode=\"system\"}[1m]))*100",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 2 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes / 1000000000) - ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes - node_memory_Slab_bytes)/ 1000000000)",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 2 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes/1000000000) - ((node_filesystem_size_bytes - node_filesystem_avail_bytes)/1000000000) ",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "UPLOAD",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 2 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "DOWNLOAD",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 2 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m])",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))*100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "ICMP/HTTPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum((rate(probe_http_duration_seconds{instance!=\"http://localhost:8080\",phase=\"processing\"}[1m]))*100)",
     "legendFormat": "processing"
    },
    {
     "expr": "sum((rate(probe_http_duration_seconds{instance!=\"http://localhost:8080\",phase=\"connect\"}[1m]))*100)",
     "legendFormat": "connect"
    },
    {
     "expr": "sum((rate(probe_http_duration_seconds{instance!=\"http://localhost:8080\",phase=\"resolve\"}[1m]))*100)",
     "legendFormat": "resolve"
    },
    {
     "expr": "sum((rate(probe_http_duration_seconds{instance!=\"http://localhost:8080\",phase=\"tls\"}[1m]))*100)",
     "legendFormat": "tls"
    },
    {
     "expr": "sum((rate(probe_http_duration_seconds{instance!=\"http://localhost:8080\",phase=\"transfer\"}[1m]))*100)",
     "legendFormat": "transfer"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "Uptime: {{alias}}"
    }
   ]
  },
  {
   "title": "Memory RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes - node_memory_Slab_bytes)",
     "legendFormat": "Usado"
    }
   ]
  },
  {
   "title": "Memory DISK",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes) ",
     "legendFormat": "Usado"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_SwapCached_bytes", "legendFormat": "Usado" }
   ]
  },
  {
   "title": "ICMP/HTTPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(probe_http_duration_seconds{instance!=\"http://localhost:8080\"}[1m]))*100",
     "legendFormat": "{{instance}} {{phase}}"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m]) /10000",
     "legendFormat": "Net"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}